### PR TITLE
Added file for vision statement

### PR DESCRIPTION
**Pull request by jyoti-bhogal**
This commit contains the link to the Vision Statement slides.

### CODE REVIEW

**Review by SaranjeetKaur — CHANGES_REQUESTED** [review]
@jyoti-bhogal thanks for this submission!

Instead of sharing this link, could you please create a folder in this repository called `/docs`, and a sub-folder in it called `/vision board`. Then you could download the slides as .pptx and upload it in the `/vision board` sub-folder.

Let me know if this helps!

**Comment by jyoti-bhogal** [comment]
Noted, thanks! Will do it.

**Comment by jyoti-bhogal** [comment]
@SaranjeetKaur I have updated my commit. And am figuring out how the changes in the latest commit would be reflected in this PR.

**Comment by jyoti-bhogal** [comment]
@SaranjeetKaur As requested, I have created a docs folder and uploaded the Vision Statement presentation in it. 
Please review and share your comments.

**Comment by SaranjeetKaur** [comment]
Looks good!

**Pull request merged**
